### ISSUE TITLE
List of statistics Tom needs for the report

### ISSUE THREAD

**Issue by TomBrown4444** [ChristinaLast/pollution_analysis_kurdistan#49]
July 2021 to now flaring count
The flaring count of the nine months leading up to July 2021
Comparisons with Iraq (like for like)
The equivalent data for methane values

**Comment by TomBrown4444** [comment]
Proximity to flaring:
- Data which indicates the presence of carcinogenic materials
- Get stats of population density
- Stats on Russian population centres proximity to gas flares versus Iraq (can use study areas)

**Comment by ChristinaLast** [comment]
Great! In terms of these I can do the following:

- Data which indicates the presence of carcinogenic materials
  - [x] I am extracting [AOD](https://developers.google.com/earth-engine/datasets/catalog/MODIS_006_MCD19A2_GRANULES) for the large rectangular regions that we discussed previously over the time period shown
- [x] Get stats of population density
  - [x] Please take a look at [this data](https://developers.google.com/earth-engine/datasets/catalog/CIESIN_GPWv411_GPW_Population_Density) for population density. I will extract this data for the study region much the same as for other satellite data, but I believe the most recent measure was on 2020, so it will not be in timeseries (i.e. there is only one value per ~900m grid cells.   
  - [x] I am keen to calculate exposure to AOD above a specific threshold which will give us an idea of total no. of people exposed to air pollution.
- Stats on Russian population centres proximity to gas flares versus Iraq (can use study areas)
  - this requires the following:
    1. Extracting all russian flares
    2. creating bespoke regions around flares that we consider the "study region"
    3. extracting all data on AOD and population denisty for these "study regions" 
    4. Calculating the exposure (e.g. the number of population intersecting areas of high AOD concentration).
This pipeline is built, but will take a long time to run because of the vast scale of Russia. We can reduce this time by:
      - reducing the size of the study region, however, this makes it difficult to compare between Iraq and Russia
      - Reducing the timeseries. if we only have select dates that we want to compare exposure, rather than over the whole timeperiod, then this will reduce processing time.

I hope that makes sense!

**Comment by ChristinaLast** [comment]
Russian issue now being addressed in #52

**Comment by ChristinaLast** [comment]
![iraq_kurdistan_russia_timeseries](https://user-images.githubusercontent.com/36204574/168498923-9c4d7c58-7e4b-4ef1-baf1-de7c936f6411.png)


![iraq_kurdistan_timeseries](https://user-images.githubusercontent.com/36204574/168498786-d1088f6b-9560-4c44-a95e-91ede68bcd00.png)

**Comment by ChristinaLast** [comment]
![iraq_kurdistan_date_timeseries](https://user-images.githubusercontent.com/36204574/168499899-0b2a15ad-37ea-423c-9af3-0ad906fad9bc.png)
